name: webview
description: Flutter webview


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^2.3.1
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher.png"
 #D:\Programme\Flutter\flutter\bin\flutter.bat --no-color pub run flutter_launcher_icons:main
flutter_native_splash:
 # color: "#42a5f5"
  background_image: "assets/launcher2.png"
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  #D:\Programme\Flutter\flutter\bin\flutter.bat --no-color pub run flutter_native_splash:create