name: leadlr
description: Flutter webview

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+6 # nächstes 3

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  webview_flutter: ^3.0.0
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2
  firebase_messaging: ^11.2.4
  firebase_core: ^1.10.6
  flutter_local_notifications: ^9.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher.png"
 #D:\Programme\Flutter\flutter\bin\flutter.bat --no-color pub run flutter_launcher_icons:main
flutter_native_splash:
  color: "#000000"
  image: "assets/launcher.png"
 # fullscreen: true
  android_gravity: center
  ios_content_mode: center
  #D:\Programme\Flutter\flutter\bin\flutter.bat --no-color pub run flutter_native_splash:create

