name: verbrauchercheck
description: Verbrauchercheck App.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  webview_flutter: ^3.0.0
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2
 # firebase_messaging: ^11.2.5
 # firebase_core: ^1.11.0
 # flutter_local_notifications: ^9.1.5
#  firebase_crashlytics: ^2.4.5
  connectivity_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher.png"
 
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/launcher.png"
  android_gravity: center
  ios_content_mode: center

